const hamburger = document.getElementById('hamburger');
const sidebar = document.getElementById('sidebar');

hamburger.addEventListener('click', () => {
    hamburger.classList.toggle('active');
    sidebar.classList.toggle('open');
});

// Objeto que contiene las canciones de cada álbum
const albums = {
    'MUNDO GUANACO (1995)': ['Dijo el droguero al drogador',
        'Desencuentro',
        'El pibe tigre',
        'Como los bueyes',
        'Voy a enloquecer',
        'El amasijo de un gran sueño',
        'De los pagos del tiempo',
        'Buitres',
        'Sentir indiano',
        'Zamba de resurrección'],
    'DEL ENTORNO (1996)': [ 'Del entorno',
        'Lucero del Alba',
        'Hacia el abismo',
        'Por nacer',
        'Amistades de tierra adentro',
        'Los delirios del defacto',
        '1999',
        'De la carne',
        'Hombre peste',
        'Rubén patagonia',
        'Presa fácil'],
    'EN VIDA (1997)': ['De los Pagos del Tiempo (Cover de José Larralde)',
        'El Pibe Tigre',
        'Lanzado al Mundo Hoy (Cover de V8)',
        'Atravesando Todo Límite (Cover de Hermética)',
        'Desencuentro',
        '1999',
        'Buitres',
        'Por Nacer',
        'Sentir Indiano',
        'Mal Bicho (Cover de Los Fabulosos Cadillacs)',
        'De Mandadores y Mandados (Cover de Iorio & Flavio)',
        'Gil Trabajador (Cover de Hermética)',
        'Moraleja (Cover de Hermética)',
        'Ayer Deseo, Hoy Realidad (Cover de Hermética)',
        'Zamba de Resurrección',
        'Dijo el Droguero al Drogador',
        'Por Tu Suerte (En estudio) (Inédito)',
        'Del Más Allá (En estudio) (Inédito)'],
    'PESO ARGENTO (1997)': [ 'Allá en Tilcara (Ricardo Iorio, Claudio Marciello)',
        'Nacido y criado en el sur (Flavio Cianciarulo)',
        'Río Paraná (Ricardo Iorio)',
        'De Mandinga y remolinos (Ricardo Iorio, Claudio Marciello)',
        'Mal bicho (Cover de Los Fabulosos Cadillacs) (Flavio Cianciarulo)',
        'Ramón, el indio hereje (Flavio Cianciarulo)',
        'Cacique Yatel (Cover de Hugo Giménez Agüero)',
        'Gil trabajador (Cover de Hermética) (Ricardo Iorio)',
        'Para pocos de los muchos (Ricardo Iorio)',
        'De mandadores y mandados (Flavio Cianciarulo, Ricardo Iorio)',
        'Virgen de los muertitos'],
    'PROFETA EN SU TIERRA (1998)': ['Presa fácil (Ricardo Iorio)',
    'Del entorno (Versión inédita) (Ricardo Iorio)',
    'Amasijo de un gran sueño (Ricardo Iorio)',
    'Voy a enloquecer (En directo) (Ricardo Iorio, Ricardo "Chofa" Moreno)',
    'Lucero del alba (Ricardo Iorio, Claudio Marciello)',
    'Hombre peste (Ricardo Iorio, Claudio Marciello)',
    'Zamba de resurrección (En directo) (Ricardo Iorio, Claudio Marciello)',
    'De la carne (Ricardo Iorio, Claudio Marciello)',
    'En las calles de Liniers (Versión inédita de Hermética) (Ricardo Iorio)',
    'Como los bueyes (Ricardo Iorio, Pedro Bonifacio Palacios)',
    'Moraleja (Versión en directo de Hermética) (Ricardo Iorio)',
    'Los delirios del defacto (Ricardo Iorio)',
    'Rubén Patagonia (En directo) (Ricardo Iorio, Claudio Marciello)',
    'Del colimba (Versión en directo de Hermética) (Ricardo Iorio)',
    'Me da pena confesarlo (Tema inédito de estudio) (Carlos Gardel)'],
    'ALMAFUERTE (1998)': ['Mano brava (Claudio Marciello)',
    'Almafuerte (Claudio Marciello)',
    'Triunfo (Claudio Marciello)',
    'Sé vos (Claudio Marciello)',
    'Niño jefe (Claudio Marciello)',
    'Memoria de siglos (Cover de Hermética) (Ricardo Iorio)',
    'Ser humano junto a los míos (Claudio Marciello)',
    'Desde el oeste (Cover de Hermética) (Ricardo Iorio)',
    'Del más allá (Claudio Marciello)',
    'Tú eres su seguridad (Cover de Hermética) (Ricardo Iorio)',
    'Ceibo (Instrumental) (Claudio Marciello)'],
    'A FONDO BLANCO (1999)': [ 'Homenaje (Ricardo Iorio, Claudio Marciello)',
        'Convide rutero (Ricardo Iorio, Claudio Marciello)',
        'Si me estás buscando (Ricardo Iorio, Claudio Marciello)',
        'A vos amigo (Ricardo Iorio)',
        'Tangolpeando (Ricardo Iorio)',
        'Aguante Bonavena (Ricardo Iorio, Claudio Marciello)',
        'El visitante (Ricardo Iorio, Claudio Marciello)',
        'Hoy es (Ricardo Iorio, Claudio Marciello)',
        'La llaga (Nacho Whisky, Claudio Marciello)',
        'Al pájaro (Ricardo Iorio)',
        'Motivo ciudadano (Instrumental) (Claudio Marciello)'],
    'PIEDRA LIBRE (2001)': [ 'Las aguas turbias suben esta vez (3:55)',
        'Orgullo argentino (3:53)',
        'Por ser yo (3:48)',
        'Allí en San Juan (4:25)',
        'Amanecer en Open Door (2:56)',
        'Regresando (2:30)',
        'De un mañana bajo tierra (2:53)',
        'Sirva otra vuelta, pulpero (Cuchilla Grande) (Diego Petru, Gabriel Tesija, Miguel Zorrilla) (3:42)',
        'Cumpliendo mi destino (4:08)',
        'Para todos mis compañeros (Instrumental)'],
    'ULTIMANDO (2003)': ['Patria al hombro (Ricardo Iorio, Claudio Marciello) (3:52)',
    'Ultranza (Ricardo Iorio, Claudio Marciello) (2:42)',
    'Todo es en vano, si no hay amor (Ricardo Iorio, Claudio Marciello) (3:34)',
    'Con rumbo al abra (Ricardo Iorio, Claudio Marciello) (4:31)',
    'Ruta 76 (Ricardo Iorio) (3:55)',
    'Del fumador (Ricardo Iorio, Claudio Marciello) (2:51)',
    'En este viaje (Ricardo Iorio, Claudio Marciello) (4:43)',
    'Yo traigo la semilla (Ricardo Iorio, Diego Petru, Claudio Marciello) (4:01)',
    'T.C. (Ricardo Iorio, Claudio Marciello) (2:33)',
    'Sojuzgados y sometidos (Ricardo Iorio, Claudio Marciello) (3:29)',
    'Como estaba ahí Dios (Cuchilla Grande)'],
    '1995 & 2005 10 AÑOS (2005)': [ 'Todo es en vano, si no hay amor (Ricardo Iorio, Claudio Marciello) (3:33)',
        'Con rumbo al abra (Ricardo Iorio, Claudio Marciello) (4:44)',
        'Patria al hombro (Ricardo Iorio, Claudio Marciello) (3:47)',
        'Mano brava (Ricardo Iorio, Claudio Marciello) (3:28)',
        'Ruta 76 (Ricardo Iorio) (4:17)',
        'Si me estás buscando (Ricardo Iorio, Claudio Marciello) (3:27)',
        'Como estaba ahí Dios (Ricardo Iorio, Claudio Marciello, Diego Petru, Gabriel Tesija) (3:27)',
        'Tangolpeando (Ricardo Iorio) (3:15)',
        'La llaga (Nacho Whisky, Claudio Marciello) (2:23)',
        'Allá en Tilcara (Ricardo Iorio, Claudio Marciello) (4:27)',
        'Para pocos de los muchos (Ricardo Iorio, Claudio Marciello) (3:22)',
        'Sé vos (Ricardo Iorio, Claudio Marciello) (4:22)',
        'Yo traigo la semilla (Ricardo Iorio, Diego Petru, Claudio Marciello) (3:57)',
        'Sentir indiano (Ricardo Iorio) (3:42)',
        '1999 (Ricardo Iorio) (3:47)',
        'Por el sudaca (Instrumental) (Claudio Marciello) (4:19)',
        'En este viaje (Ricardo Iorio, Claudio Marciello) (5:14)',
        'Hoy es (Ricardo Iorio, Claudio Marciello) (3:04)',
        'Ser humano junto a los míos (3:23)',
        'Convide rutero (Ricardo Iorio, Claudio Marciello) (4:04)',
        'Almafuerte (Ricardo Iorio, Claudio Marciello)'],
    'TORO Y PAMPA (2006)': ['Debes saberlo (Ricardo Iorio, Claudio Marciello) (3:25)',
    'Pensando en llegar (Ricardo Iorio, Claudio Marciello) (3:26)',
    'De la escuelita (Ricardo Iorio, Claudio Marciello) (3:29)',
    'Unas estrofas más (Ricardo Iorio, Claudio Marciello) (4:06)',
    'La máquina de picar carne (Ricardo Iorio, Claudio Marciello) (3:22)',
    'Dónde está mi corazón (Ricardo Iorio, Claudio Marciello) (3:10)',
    'En el siglo del gran reviente (Ricardo Iorio, Claudio Marciello) (2:59)',
    'Vencer el tiempo (Ricardo Iorio, Claudio Marciello) (3:58)',
    'Toro y pampa (Ricardo Iorio) (3:31)',
    'Cosas que pueden pasar (Incluye cita a "Fogonera" de José Larralde) (Ricardo Iorio · José Larralde, Claudio Marciello) (3:13)',
    'Sopla el pampero (Instrumental) (Claudio Marciello) (1:19)',
    'Sé vos (Versión acústica) (Ricardo Iorio, Claudio Marciello) (3:38)',
    'Por ser yo (En vivo) (Ricardo Iorio) (3:47)',
    'Toro y pampa (En vivo) (Ricardo Iorio)'],
    'AYER DESEO HOY REALIDAD (2008)': [ 'Hace casi 2000 años (Edelmiro Molinari, Color Humano)',
        'Toma el tren hacia el sur (Luis Alberto Spinetta, Almendra)',
        'Blues del atardecer (Willy Gardi/Eduardo Frezza, El Reloj)',
        'Solitario Juan (Pappo, Pappo\'s Blues)',
        'Ritmo y blues con armónicas (Ricardo Soulé, Vox Dei)',
        'Durazno sangrando (Luis Alberto Spinetta, Invisible)',
        'Jugo de tomate (Javier Martínez, Manal)',
        'Un amigo de verdad (Roque Narvaja, Roque Narvaja)',
        'Rock de la selva madre (Luis Alberto Spinetta, Pescado Rabioso)',
        'Tontos (Billy Bond/Alejandro Medina/Claudio Gabis/Jorge Álvarez, Billy Bond y La Pesada del Rock and Roll)',
        'Vine cruzando el mar (Pappo, Aeroblus)',
        'Imágenes fugaces (Esteban Salvi, La Moto Rock Callejero)',
        'Mariposas de madera (Miguel Abuelo, Miguel Abuelo)'],
    'EN VIVO OBRAS (2010)': ['El amasijo de un gran sueño',
    'Niño jefe',
    'Todo es en vano, si no hay amor',
    'Debes saberlo',
    'Yo traigo la semilla',
    'Toro y pampa',
    'Sé vos',
    'Triunfo',
    'Si me estás buscando',
    'Orgullo Argentino',
    'Patria al hombro',
    'Pensando en llegar',
    'De la carne',
    'La máquina de picar carne',
    'De pie',
    'Homenaje',
    'De la carne',
    'A vos amigo'],
    'TRILLANDO LA FINA (2012)': ['Muere, Monstruo Muere',
    'Trillando la Fina',
    'Pa Pelusa',
    'Si Me Ves Volver',
    'Pa\'l Recuerdo',
    'Ciudad de Rosario',
    'Mi Credo',
    'La Llaga (Nueva versión)',
    'Glifosateando',
    'Mamuil Mapu',
    'Caballo Negro'],
    'EN VIVO MICROESTADIO MALVINAS (2012)': [ 'La máquina de picar carne',
        'Con rumbo al abra',
        'Muere monstruo muere',
        'Sentir indiano',
        'El visitante',
        'Encuentro',
        'Presa fácil',
        'Pal recuerdo',
        'Caballo negro',
        'Mi credo',
        'Allá en Tilcara',
        'Pa Pelusa',
        'Trillando la fina',
        'Si me ves volver',
        'Ciudad de Rosario',
        'Toro y pampa',
        'Almafuerte'],
    'TANGOS Y MILONGAS, VOL.1 (2014)': [ 'El adiós de Gabino Ezeiza (1933) - Enrique Maciel / Héctor Pedro Blomberg',
        'Martirio (1940) - Enrique Santos Discépolo',
        'Sabe don (1956) - Juan Miguel Rodríguez / Justo Ricardo Thompson',
        'El último viaje (1965) - Rogelio Araya / Francisco Gandola',
        'En un feca (1924) - Anónimo',
        'Más allá (1939) - Joaquín Mora / José María Contursi',
        'Y a mí qué? (1962) - Aníbal Troilo / Cátulo Castillo',
        'Vieja Recova (1930) - Rodolfo Sciammarella / Enrique Cadícamo',
        'No te apures Carablanca (1942) - Roberto Garza / Carlos Bahr',
        'En la vía (1929) - Nicolás Vaccaro / Eduardo Escaris Méndez',
        'Tangolpeando (1999) - Ricardo Iorio / Claudio Marciello',
        'Gol argentino (1978) - Héctor Marcó',
        'No la quiero más (1951) - Alberto Mastra'],
    'ATESORANDO LOS CIELOS (2015)': [ 'Guitarrera - 4:56',
        'Preguntando lo que todos saben (Budgie) - 3:02',
        'Robó un auto (Hermética) - 3:21',
        'Quiero ser como usted (Roxette) - 4:15',
        'The Krochik - 3:43',
        'Justo que te vas - 4:46',
        'No me cambiarán (Black Sabbath) - 6:17',
        'De mi rumbear al sur - 2:49',
        'Ideando la fuga (V8) - 2:43',
        'Otro día para ser (Intro) (Hermética) - 1:35',
        'Uno (Enrique Santos Discépolo, Mariano Mores)'],
    'EN VIVO ALL BOYS (2022)': [ 'Patria al Hombro (En Vivo All Boys)',
        'Desde el Oeste (En Vivo All Boys)',
        'Del Mas Allá (En Vivo All Boys)',
        'Sé Vos (En Vivo All Boys)',
        'Triunfo (En Vivo All Boys)',
        'Pal Recuerdo (En Vivo All Boys)',
        'Ceibo (En Vivo All Boys)',
        'Caballo Negro (En Vivo All Boys)',
        'Mi Credo (En Vivo All Boys)',
        'Zamba de Resurrección (En Vivo All Boys)',
        'En la Via (En Vivo All Boys)',
        'El Ultimo Viaje (En Vivo All Boys)',
        'Toro y Pampa (En Vivo All Boys)',
        'Pa\' Pelusa (En Vivo All Boys)',
        'Trillando la Fina (En Vivo All Boys)',
        'Si Me Ves Volver (En Vivo All Boys)',
        'Ciudad de Rosario (En Vivo All Boys)',
        'Vida Impersonal (En Vivo All Boys)',
        'La Revancha de América (En Vivo All Boys)',
        'Del Camionero (En Vivo All Boys)',
        'Cuando Duerme la Ciudad (En Vivo All Boys)',
        'Olvídalo y Volverá por Más (En Vivo All Boys)',
        'Deseando Destruir y Matar (En Vivo All Boys)',
        'Cautivos del Sistema (En Vivo All Boys)',
        'Muy Cansado Estoy (En Vivo All Boys)',
        'Destrucción (En Vivo All Boys)',
        'A Vos Amigo (En Vivo All Boys)'],
    'AVIVANDO LA LLAMA DE LA LEY NATURAL (2022)': [ 'De Pismanta A Bauchaceta',
        'Para Que No Caigas',
        'Desde El Oeste',
        'El Oficio De Cantor',
        'Yo No Lo Haré',
        'En Las Calles De Liniers',
        'Cuando Duerme La Ciudad',
        'Hombres De Hierro',
        'Para Vos',
        'Diferencias',
        'Vida Impersonal',
        'Del Camionero',
        'Gol Argentino',
        'Tangolpeando',
        'Cautivos Del Sistema',
        'Quién Quiera Oir Que Oiga',
        'Morir Al Lado De Mi Amor',
        'Me Gusta La Gente Simple']
};

// Contenedor donde se mostrarán las canciones
const songListContainer = document.getElementById('song-list');

// Función para actualizar la lista de canciones
function updateSongList(albumName) {
    
    songListContainer.innerHTML = '';

    // Limpiar espacios y capitalización en el nombre del álbum
    albumName = albumName.trim().toUpperCase();

    // Obtener las canciones del álbum seleccionado
    const songs = albums[albumName];

    if (songs) {
        // Crear un elemento de lista para cada canción
        songs.forEach(song => {
            const songItem = document.createElement('li');
            songItem.textContent = song;
            songListContainer.appendChild(songItem);
        });
    } else {
        songListContainer.innerHTML = '<li>No hay canciones disponibles para este álbum.</li>';
    }
}

// Capturar los álbumes en la sección principal
const albumElements = document.querySelectorAll('.album');

// Añadir evento de clic a cada álbum en la página principal
albumElements.forEach(albumElement => {
    albumElement.addEventListener('click', () => {
        const albumName = albumElement.querySelector('p').textContent.trim(); 
        updateSongList(albumName);
    });
});


document.getElementById("lastModified").textContent = "Last Modification: " + document.lastModified;
